import uuid
import logging
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Depends, UploadFile, File, Form, HTTPException
from pydantic import BaseModel

from core import db, current_team_or_admin
from services.import_service import (
    parse_file, auto_detect_headers, apply_transforms,
    validate_and_detect_duplicates, rollback_import_records
)
from services.import_sessions import (
    create_import_session, finalize_import_session
)
from services.import_validators import compute_file_checksum

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/admin/imports", tags=["imports"])

class PreviewRequest(BaseModel):
    raw_rows: List[Dict[str, Any]]
    field_mapping: Dict[str, Optional[str]]

class ValidateRequest(BaseModel):
    raw_rows: List[Dict[str, Any]]
    field_mapping: Dict[str, Optional[str]]

class ImportExecuteRequest(BaseModel):
    filename: str
    records: List[Dict[str, Any]]
    dup_actions: Dict[str, Any]
    file_checksum: Optional[str] = None

class PresetSaveRequest(BaseModel):
    name: str
    field_mapping: Dict[str, Optional[str]]

class LabelRulePayload(BaseModel):
    field: str
    operator: str
    value: str
    label: str

class MediaConfigPayload(BaseModel):
    max_size_bytes: int
    allowed_mime_types: List[str]

@router.post("/upload")
async def upload_import_file(
    file: UploadFile = File(...),
    admin: dict = Depends(current_team_or_admin)
):
    """Upload a CSV or XLSX sheet and extract headers, metadata, checksum hash, and preview data."""
    try:
        content = await file.read()
        filename = file.filename or "import.csv"
        size = len(content)
        
        if size > 10 * 1024 * 1024:
            raise HTTPException(400, "File size exceeds maximum limit of 10MB")
            
        checksum = compute_file_checksum(content)
        
        # Check if checksum was already imported
        existing_history = await db.import_history.find_one({"file_checksum": checksum})
        is_duplicate_file = existing_history is not None
        duplicate_filename = existing_history.get("filename") if is_duplicate_file else None
        
        headers, raw_rows = parse_file(content, filename)
        detected_mapping = auto_detect_headers(headers)
        sample_rows = raw_rows[:10]
        
        return {
            "filename": filename,
            "size": size,
            "row_count": len(raw_rows),
            "file_checksum": checksum,
            "is_duplicate_file": is_duplicate_file,
            "duplicate_filename": duplicate_filename,
            "headers": headers,
            "detected_mapping": detected_mapping,
            "raw_rows": raw_rows,
            "sample_rows": sample_rows
        }
    except Exception as e:
        logger.error(f"[Imports] Upload failed: {e}", exc_info=True)
        raise HTTPException(400, f"Failed to parse file: {str(e)}")

@router.post("/preview")
async def preview_transforms_api(
    req: PreviewRequest,
    admin: dict = Depends(current_team_or_admin)
):
    """Dry-run transformations on sample rows, presenting the exact constructed MongoDB document JSON."""
    preview = []
    for idx, row in enumerate(req.raw_rows[:100]):
        transformed = apply_transforms(row, req.field_mapping)
        
        # Build exact Mongo document shape representation
        doc_preview = {
            "id": f"autogenerated-uuid-placeholder",
            **transformed,
            "import_id": "session-uuid-placeholder",
            "created_at": datetime.now(timezone.utc).isoformat(),
            "updated_at": datetime.now(timezone.utc).isoformat(),
            "status": "SUBMITTED",
            "approval_status": "approved",
            "created_by": admin["id"],
            "media": transformed.get("media", []),
            "availability": "available"
        }
        
        preview.append({
            "row_number": idx + 2,
            "original": {k: str(v) for k, v in row.items() if v is not None},
            "transformed": transformed,
            "mongo_document": doc_preview
        })
    return preview

@router.post("/validate")
async def validate_sheet_api(
    req: ValidateRequest,
    admin: dict = Depends(current_team_or_admin)
):
    """Validate all rows and detect database duplicates."""
    try:
        results = await validate_and_detect_duplicates(req.raw_rows, req.field_mapping)
        return results
    except Exception as e:
        logger.error(f"[Imports] Validation failed: {e}", exc_info=True)
        raise HTTPException(500, f"Validation failed: {str(e)}")

@router.post("/import")
async def execute_import_api(
    req: ImportExecuteRequest,
    admin: dict = Depends(current_team_or_admin)
):
    """Enqueues the import job to the persistent MongoDB task queue. Enforces a Global Ingestion Lock."""
    # Enforce Global Ingestion Lock: check if there is an active import running
    active_job = await db.import_sessions.find_one({"status": {"$in": ["queued", "processing"]}})
    if active_job:
        raise HTTPException(
            400, 
            f"Global Ingestion Lock active: Another import pipeline ({active_job.get('filename')}) is currently being processed by the worker queue."
        )

    session_id = await create_import_session(
        filename=req.filename,
        total_rows=len(req.records),
        records=req.records,
        dup_actions=req.dup_actions,
        admin_id=admin["id"],
        admin_email=admin.get("email")
    )
    
    # Save the file checksum on the session and history placeholder
    if req.file_checksum:
        await db.import_sessions.update_one({"_id": session_id}, {"$set": {"file_checksum": req.file_checksum}})

    return {
        "import_id": session_id,
        "status": "queued",
        "message": "Import job successfully queued in persistent worker database."
    }

@router.get("/sessions/{session_id}")
async def get_session_status(
    session_id: str,
    admin: dict = Depends(current_team_or_admin)
):
    """Poll progress details, failure logs, and processed record counts for an active session."""
    session = await db.import_sessions.find_one({"_id": session_id}, {"snapshots": 0})
    if not session:
        raise HTTPException(404, "Import session not found")
    return session

@router.get("/history")
async def get_import_history(
    admin: dict = Depends(current_team_or_admin)
):
    """Retrieve history list of past imports."""
    cursor = db.import_history.find({}, {"_id": 0}).sort("created_at", -1)
    return await cursor.to_list(length=100)

@router.get("/presets")
async def get_mapping_presets(
    admin: dict = Depends(current_team_or_admin)
):
    """Fetch saved field mapping presets."""
    cursor = db.import_presets.find({}, {"_id": 0})
    return await cursor.to_list(length=50)

@router.post("/presets")
async def save_mapping_preset(
    req: PresetSaveRequest,
    admin: dict = Depends(current_team_or_admin)
):
    """Save field mapping preset for quick re-use."""
    preset = {
        "id": str(uuid.uuid4()),
        "name": req.name,
        "field_mapping": req.field_mapping,
        "created_at": datetime.now(timezone.utc).isoformat()
    }
    await db.import_presets.insert_one(preset)
    return {"success": True, "preset": preset}

@router.get("/label-rules")
async def get_label_rules(
    admin: dict = Depends(current_team_or_admin)
):
    """Fetch all auto-labeling rules."""
    cursor = db.label_rules.find({})
    res = await cursor.to_list(length=100)
    # Serialize ObjectId to string
    for r in res:
        r["id"] = str(r["_id"])
        r.pop("_id", None)
    return res

@router.post("/label-rules")
async def add_label_rule(
    payload: LabelRulePayload,
    admin: dict = Depends(current_team_or_admin)
):
    """Create a new auto-label rule."""
    rule_doc = {
        "field": payload.field,
        "operator": payload.operator,
        "value": payload.value,
        "label": payload.label
    }
    await db.label_rules.insert_one(rule_doc)
    return {"success": True}

@router.delete("/label-rules/{rule_id}")
async def delete_label_rule(
    rule_id: str,
    admin: dict = Depends(current_team_or_admin)
):
    """Delete an auto-label rule."""
    from bson import ObjectId
    try:
        await db.label_rules.delete_one({"_id": ObjectId(rule_id)})
    except Exception:
        raise HTTPException(400, "Invalid rule ID format")
    return {"success": True}

@router.get("/media-config")
async def get_media_config(
    admin: dict = Depends(current_team_or_admin)
):
    """Retrieve the media validator configuration."""
    config = await db.media_validation_config.find_one({}, {"_id": 0})
    if not config:
        config = {
            "max_size_bytes": 200 * 1024 * 1024,
            "allowed_mime_types": ["image/", "video/", "application/pdf"]
        }
    return config

@router.post("/media-config")
async def update_media_config(
    payload: MediaConfigPayload,
    admin: dict = Depends(current_team_or_admin)
):
    """Update the media validator limits."""
    await db.media_validation_config.update_one(
        {},
        {"$set": {
            "max_size_bytes": payload.max_size_bytes,
            "allowed_mime_types": payload.allowed_mime_types
        }},
        upsert=True
    )
    return {"success": True}

@router.get("/lookup-tables/{table_name}")
async def get_lookup_table(
    table_name: str,
    admin: dict = Depends(current_team_or_admin)
):
    """Retrieve items from a lookup collection (e.g. city_aliases, language_aliases)."""
    coll_name = f"lookup_{table_name}"
    cursor = db[coll_name].find({}, {"_id": 0})
    return await cursor.to_list(length=100)

@router.post("/lookup-tables/{table_name}")
async def add_lookup_alias(
    table_name: str,
    payload: Dict[str, str],
    admin: dict = Depends(current_team_or_admin)
):
    """Insert or update a lookup table alias mapping."""
    coll_name = f"lookup_{table_name}"
    alias = payload.get("alias")
    canonical = payload.get("canonical")
    if not alias or not canonical:
        raise HTTPException(400, "Missing alias or canonical value")
        
    await db[coll_name].update_one(
        {"alias": alias.lower()},
        {"$set": {"alias": alias.lower(), "canonical": canonical}},
        upsert=True
    )
    return {"success": True}

@router.get("/{import_id}")
async def get_import_report(
    import_id: str,
    admin: dict = Depends(current_team_or_admin)
):
    """Retrieve specific import report by ID."""
    report = await db.import_history.find_one({"id": import_id}, {"_id": 0})
    if not report:
        raise HTTPException(404, "Import report not found")
    return report

@router.post("/{import_id}/rollback")
async def rollback_import_api(
    import_id: str,
    admin: dict = Depends(current_team_or_admin)
):
    """Rollback an import, restoring modified talents to their exact previous state and removing new records."""
    try:
        total_restored = await rollback_import_records(import_id)
        
        await db.import_history.update_one(
            {"id": import_id},
            {"$set": {"status": "rolled_back", "rolled_back_at": datetime.now(timezone.utc).isoformat()}}
        )
        
        return {
            "success": True,
            "deleted_count": total_restored,
            "message": f"Successfully rolled back {total_restored} talent records to their pre-import state."
        }
    except Exception as e:
        logger.error(f"[Imports] Rollback failed for import_id={import_id}: {e}", exc_info=True)
        raise HTTPException(500, f"Rollback failed: {str(e)}")
