"""Talent Media Download Link.

A private, opaque, LIVE link to one talent's Global Talent media (Indian Look
Images, Western Look Images, Additional Portfolio, Introduction Video), sent
as a second WhatsApp message right after the submission form, plus the public
endpoints that back the client-facing media page.

Design (all reuse — no parallel media system):
  * Media source  : `db.talents[...].media[]` — the SAME array, categories and
                    ordering the Global Talent profile page renders. Nothing is
                    copied or snapshotted; every request reads the talent fresh.
  * Access control: an opaque per-talent token (`media_download_token`, 192-bit,
                    minted once, never regenerated by the toggle) plus an
                    `media_download_enabled` flag. BOTH are checked on EVERY
                    request, so switching the flag OFF kills links already sent
                    and switching it back ON revives the very same link.
                    Missing flag == ON (default); only an explicit False is OFF.
  * Downloads     : individual files stream through the backend (Cloudinary /
                    Stream URLs are resolved server-side and never returned;
                    the browser CSP does not permit direct cross-origin fetch).
                    "Download All" is a CONSTANT-MEMORY streaming ZIP — one file
                    in flight, 64 KiB chunks, STORED (no recompression) — NOT
                    the buffer-everything-in-RAM approach used by the client
                    link ZIP in routers/links.py (deliberately not reused).
  * WhatsApp      : `enqueue_media_link_message` is called by the existing
                    submission-notification task AFTER the form message(s), in
                    its own try/except, and is made idempotent per submission
                    event via `talent_media_link_events` (unique event_key).
"""
import logging
import os
import re
import secrets
import string
import struct
import time
import uuid
import zlib
from typing import Any, AsyncIterator, Dict, List, Optional, Tuple
from urllib.parse import quote

import asyncio
import httpx
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse
from starlette.background import BackgroundTask
from pymongo.errors import DuplicateKeyError
from pydantic import BaseModel

from core import (
    _now,
    _public_media,
    client_ip,
    current_team_or_admin,
    db,
    enrich_talent,
    rate_limit_ok,
)
from routers.links import _resolve_video_download_url

logger = logging.getLogger("talentgram")

router = APIRouter(prefix="/api", tags=["talent-media"])

MEDIA_LINK_BASE_URL = os.environ.get("TALENT_MEDIA_BASE_URL", "https://links.talentgramagency.com").rstrip("/")

_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]{20,64}$")
_UNAVAILABLE = "This media link is not available."

# Display order + labels mirror TalentEdit.jsx's media sections exactly.
_SECTIONS: List[Tuple[str, str, str]] = [
    # (response key, stored media category, label)
    ("indian", "indian", "Indian Look Images"),
    ("western", "western", "Western Look Images"),
    ("portfolio", "portfolio", "Additional Portfolio"),
]
_ZIP_FOLDERS = {
    "indian": "Indian Look Images",
    "western": "Western Look Images",
    "portfolio": "Additional Portfolio",
    "video": "Introduction Video",
}
_BLOCKED_STATUSES = {"archived", "merged"}
_IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".webp", ".heic", ".heif", ".gif")

_CHUNK = 64 * 1024
# Concurrent "Download All" streams per process — a hard resource bound.
_ZIP_MAX_CONCURRENT = int(os.environ.get("TALENT_MEDIA_ZIP_MAX_CONCURRENT", "3"))
_zip_slots = asyncio.Semaphore(_ZIP_MAX_CONCURRENT)
_MAX_ZIP_BYTES = 0xFFFFFFFF - (1 << 20)  # stay inside plain (non-zip64) ZIP limits


# ---------------------------------------------------------------------------
# Names / link helpers
# ---------------------------------------------------------------------------
def short_talent_name(name: Optional[str]) -> str:
    """'Angela Kumar' -> 'Angela K'. Everything before the last word is kept
    (multi-word first names stay whole); only the last word is reduced to its
    initial. A single-word name is returned as-is. Never exposes the surname."""
    parts = (name or "").split()
    if not parts:
        return "Talent"
    if len(parts) == 1:
        return parts[0]
    return f"{' '.join(parts[:-1])} {parts[-1][0].upper()}"


def media_link_url(token: str) -> str:
    return f"{MEDIA_LINK_BASE_URL}/talent-media/{token}"


def build_media_link_message(talent_name: Optional[str], token: str) -> str:
    return (
        f"Talentgram X {short_talent_name(talent_name)}\n\n"
        f"Kindly click the link to download pictures and introduction video:\n\n"
        f"{media_link_url(token)}"
    )


def is_media_download_enabled(talent: Optional[dict]) -> bool:
    """Missing flag == ON (default). Only an explicit False disables."""
    return (talent or {}).get("media_download_enabled") is not False


def _safe_filename(s: str) -> str:
    cleaned = "".join(c for c in (s or "") if c.isalnum() or c in " -_.").strip()
    return cleaned or "media"


# ---------------------------------------------------------------------------
# Token + indexes
# ---------------------------------------------------------------------------
_indexes_ready = False


async def _ensure_indexes() -> None:
    global _indexes_ready
    if _indexes_ready:
        return
    try:
        await db.talents.create_index(
            "media_download_token", unique=True, name="media_download_token_unique",
            partialFilterExpression={"media_download_token": {"$type": "string"}},
        )
        await db.talent_media_link_events.create_index("event_key", unique=True, name="event_key_unique")
        _indexes_ready = True
    except Exception:
        logger.exception("talent_media index creation failed (non-fatal)")


_TOKEN_ALPHABET = string.ascii_letters + string.digits


def _new_token() -> str:
    """32 chars of [A-Za-z0-9] (~190 bits). Alphanumeric only on purpose: a
    '-' or '_' at the end of a pasted URL is the classic way chat apps
    mis-linkify, and the token is read by machines, not people."""
    return "".join(secrets.choice(_TOKEN_ALPHABET) for _ in range(32))


async def ensure_token(tid: str) -> Optional[str]:
    """Return the talent's media token, minting it exactly once (race-safe:
    the conditional update only ever succeeds for the first writer)."""
    await _ensure_indexes()
    t = await db.talents.find_one({"id": tid}, {"_id": 0, "media_download_token": 1})
    if t is None:
        return None
    if t.get("media_download_token"):
        return t["media_download_token"]
    await db.talents.update_one(
        {"id": tid, "media_download_token": {"$in": [None, ""]}},
        {"$set": {"media_download_token": _new_token()}},
    )
    t = await db.talents.find_one({"id": tid}, {"_id": 0, "media_download_token": 1})
    return (t or {}).get("media_download_token")


async def _talent_for_token(token: str) -> dict:
    """Resolve token -> talent, enforcing the toggle EVERY call. Invalid,
    unknown, disabled and archived/merged all return the same 404 so the
    endpoint reveals nothing about which case applied."""
    if not token or not _TOKEN_RE.match(token):
        raise HTTPException(404, _UNAVAILABLE)
    await _ensure_indexes()
    talent = await db.talents.find_one(
        {"media_download_token": token},
        {"_id": 0, "id": 1, "name": 1, "media": 1, "cover_media_id": 1, "status": 1, "media_download_enabled": 1},
    )
    if (
        not talent
        or not is_media_download_enabled(talent)
        or str(talent.get("status") or "").lower() in _BLOCKED_STATUSES
    ):
        raise HTTPException(404, _UNAVAILABLE)
    return talent


def _rate_limit(request: Request, bucket: str, limit: int, window: float = 60.0) -> None:
    if not rate_limit_ok(f"talent-media:{bucket}:{client_ip(request)}", limit, window):
        raise HTTPException(429, "Too many requests. Please wait a moment and try again.")


# ---------------------------------------------------------------------------
# Canonical media selection (mirrors the Global Talent profile)
# ---------------------------------------------------------------------------
def _visible(m: dict) -> bool:
    # Same "hidden/internal" exclusion the client links apply.
    return bool(m.get("url")) and m.get("client_visible") is not False and m.get("internal_only") is not True


def _ext_for(m: dict, is_video: bool) -> str:
    url = (m.get("url") or "").split("?")[0]
    ext = os.path.splitext(url)[1].lower()
    if is_video:
        return ".mp4" if ext in ("", ".m3u8", ".mpd") else ext
    return ext if ext in _IMAGE_EXTS else ".jpg"


def _collect(talent: dict) -> Dict[str, Any]:
    """{'indian':[media...], 'western':[...], 'portfolio':[...], 'video': media|None}
    in stored (profile) order, from the raw talent document."""
    media = [m for m in (talent.get("media") or []) if _visible(m)]
    out: Dict[str, Any] = {key: [m for m in media if m.get("category") == cat] for key, cat, _ in _SECTIONS}
    videos = [m for m in media if m.get("category") == "video"]
    out["video"] = videos[0] if videos else None  # profile shows videoMedia[0]
    return out


def _item(m: dict, key: str, idx: int, display_name: str, is_video: bool) -> dict:
    pub = _public_media(m)
    label = "introduction-video" if is_video else f"image-{idx:02d}"
    fn = f"{_safe_filename(display_name)} - {_ZIP_FOLDERS[key]} - {label}{_ext_for(m, is_video)}"
    return {
        "id": m.get("id"),
        "kind": "video" if is_video else "image",
        "url": pub.get("url"),
        "poster_url": pub.get("poster_url") or pub.get("thumbnail_url"),
        "duration": pub.get("duration"),
        "content_type": m.get("content_type"),
        "original_filename": m.get("original_filename"),
        "created_at": m.get("created_at"),
        "filename": fn,
    }


def build_media_view(talent: dict) -> dict:
    enriched = enrich_talent({"media": list(talent.get("media") or []), "cover_media_id": talent.get("cover_media_id")})
    shaped = {**talent, "media": enriched["media"]}
    groups = _collect(shaped)
    display = short_talent_name(talent.get("name"))
    sections = []
    total = 0
    for key, _cat, label in _SECTIONS:
        items = [_item(m, key, i, display, False) for i, m in enumerate(groups[key], 1)]
        total += len(items)
        sections.append({"key": key, "label": label, "items": items})
    video = _item(groups["video"], "video", 1, display, True) if groups["video"] else None
    if video:
        total += 1
    return {
        "talent": {"name": display},
        "sections": sections,
        "video": video,
        "total": total,
    }


# ---------------------------------------------------------------------------
# Admin: toggle
# ---------------------------------------------------------------------------
class MediaDownloadToggleIn(BaseModel):
    enabled: bool


@router.patch("/talents/{tid}/media-download")
async def set_media_download(tid: str, payload: MediaDownloadToggleIn, admin: dict = Depends(current_team_or_admin)):
    """Flip the Media Download Link toggle. The token is minted once (so the
    SAME link survives OFF→ON) and never regenerated here."""
    existing = await db.talents.find_one({"id": tid}, {"_id": 0, "id": 1})
    if not existing:
        raise HTTPException(404, "Talent not found")
    token = await ensure_token(tid)
    await db.talents.update_one({"id": tid}, {"$set": {"media_download_enabled": bool(payload.enabled)}})
    logger.info("talent media link toggled: talent=%s enabled=%s by=%s", tid, payload.enabled, admin.get("email"))
    return {"enabled": bool(payload.enabled), "token": token, "url": media_link_url(token) if token else None}


# ---------------------------------------------------------------------------
# Public: page data
# ---------------------------------------------------------------------------
@router.get("/public/talent-media/{token}")
async def get_talent_media(token: str, request: Request):
    _rate_limit(request, "page", 120)
    talent = await _talent_for_token(token)
    return JSONResponse(build_media_view(talent), headers={"Cache-Control": "no-store"})


# ---------------------------------------------------------------------------
# Public: one file
# ---------------------------------------------------------------------------
def _find_media(talent: dict, media_id: str) -> Tuple[Optional[dict], Optional[str], bool]:
    groups = _collect(talent)
    for key in ("indian", "western", "portfolio"):
        for m in groups[key]:
            if m.get("id") == media_id:
                return m, key, False
    v = groups["video"]
    if v and v.get("id") == media_id:
        return v, "video", True
    return None, None, False


async def _upstream_url(client: httpx.AsyncClient, m: dict, is_video: bool) -> Optional[str]:
    if is_video:
        return await _resolve_video_download_url(client, m, m.get("url"))
    return m.get("url")


@router.get("/public/talent-media/{token}/file/{media_id}")
async def download_talent_media_file(token: str, media_id: str, request: Request):
    _rate_limit(request, "file", 120)
    talent = await _talent_for_token(token)
    m, key, is_video = _find_media(talent, media_id)
    if not m:
        raise HTTPException(404, _UNAVAILABLE)

    client = httpx.AsyncClient(follow_redirects=True, timeout=httpx.Timeout(60.0, connect=10.0))
    try:
        upstream = await _upstream_url(client, m, is_video)
        if not upstream:
            raise HTTPException(404, "Media unavailable")
        fwd = {}
        if request.headers.get("range"):
            fwd["Range"] = request.headers["range"]
        resp = await client.send(client.build_request("GET", upstream, headers=fwd), stream=True)
    except HTTPException:
        await client.aclose()
        raise
    except Exception:
        await client.aclose()
        logger.exception("talent media file upstream fetch failed")
        raise HTTPException(502, "Unable to load media")

    if resp.status_code not in (200, 206):
        code = resp.status_code
        await resp.aclose()
        await client.aclose()
        raise HTTPException(502 if code >= 500 else 404, "Media unavailable")

    display = short_talent_name(talent.get("name"))
    idx = 1
    if not is_video:
        idx = 1 + [x.get("id") for x in _collect(talent)[key]].index(media_id)
    label = "introduction-video" if is_video else f"image-{idx:02d}"
    up_ext = os.path.splitext((upstream or "").split("?")[0])[1].lower() if is_video else ""
    ext = (up_ext if up_ext and up_ext != ".m3u8" else _ext_for(m, is_video))
    disp_name = f"{_safe_filename(display)} - {_ZIP_FOLDERS[key]} - {label}{ext}"
    headers = {
        "Content-Disposition": f"attachment; filename=\"{disp_name.encode('ascii', 'ignore').decode() or 'media'}\"; filename*=UTF-8''{quote(disp_name)}",
        "Accept-Ranges": resp.headers.get("accept-ranges", "bytes"),
        "Cache-Control": "private, no-store",
        "X-Content-Type-Options": "nosniff",
    }
    for h in ("content-length", "content-range"):
        if h in resp.headers:
            headers[h.title()] = resp.headers[h]

    async def _body():
        try:
            async for chunk in resp.aiter_raw(chunk_size=_CHUNK):
                yield chunk
        finally:
            await resp.aclose()
            await client.aclose()

    return StreamingResponse(
        _body(), status_code=resp.status_code,
        media_type=resp.headers.get("content-type") or ("video/mp4" if is_video else "image/jpeg"),
        headers=headers,
    )


# ---------------------------------------------------------------------------
# Public: Download All — constant-memory streaming ZIP
# ---------------------------------------------------------------------------
def _dos_datetime(ts: Optional[float] = None) -> Tuple[int, int]:
    t = time.localtime(ts or time.time())
    dos_time = (t.tm_hour << 11) | (t.tm_min << 5) | (t.tm_sec // 2)
    dos_date = ((max(t.tm_year, 1980) - 1980) << 9) | (t.tm_mon << 5) | t.tm_mday
    return dos_time, dos_date


class ZipTooLarge(Exception):
    pass


async def stream_zip(entries: List[Tuple[str, Any]]) -> AsyncIterator[bytes]:
    """Yield a ZIP (STORED, data-descriptor) built from `entries` =
    [(arcname, async-iterator-factory)] one entry at a time. Memory is O(chunk).
    A source failure mid-entry RAISES (aborting the response) so the client
    never receives a seemingly-valid archive that is missing files: the central
    directory is only emitted after every entry completed."""
    flags = 0x0808  # bit3: sizes in data descriptor; bit11: UTF-8 names
    dos_time, dos_date = _dos_datetime()
    offset = 0
    central: List[bytes] = []
    for arcname, factory in entries:
        name_b = arcname.encode("utf-8")
        header = struct.pack("<IHHHHHIIIHH", 0x04034B50, 20, flags, 0, dos_time, dos_date, 0, 0, 0, len(name_b), 0) + name_b
        local_offset = offset
        yield header
        offset += len(header)
        crc = 0
        size = 0
        async for chunk in factory():
            if not chunk:
                continue
            crc = zlib.crc32(chunk, crc)
            size += len(chunk)
            if offset + size > _MAX_ZIP_BYTES:
                raise ZipTooLarge()
            yield chunk
        offset += size
        desc = struct.pack("<IIII", 0x08074B50, crc & 0xFFFFFFFF, size, size)
        yield desc
        offset += len(desc)
        central.append(
            struct.pack("<IHHHHHHIIIHHHHHII", 0x02014B50, 20, 20, flags, 0, dos_time, dos_date,
                        crc & 0xFFFFFFFF, size, size, len(name_b), 0, 0, 0, 0, 0, local_offset) + name_b
        )
    cd_offset = offset
    cd = b"".join(central)
    yield cd
    yield struct.pack("<IHHHHIIH", 0x06054B50, 0, 0, len(central), len(central), len(cd), cd_offset, 0)


def _upstream_factory(client: httpx.AsyncClient, url: str):
    async def gen():
        last = None
        for attempt in range(2):
            started = False
            try:
                async with client.stream("GET", url) as r:
                    if r.status_code != 200:
                        last = f"HTTP {r.status_code}"
                        continue
                    async for chunk in r.aiter_bytes(chunk_size=_CHUNK):
                        started = True
                        yield chunk
                    return
            except Exception as e:  # noqa: BLE001
                if started:
                    raise  # bytes already sent: cannot retry mid-entry
                last = str(e)
        raise RuntimeError(f"upstream fetch failed: {last}")
    return gen


@router.get("/public/talent-media/{token}/download-all")
async def download_all_talent_media(token: str, request: Request):
    _rate_limit(request, "zip", 10)
    talent = await _talent_for_token(token)
    groups = _collect(talent)
    display = short_talent_name(talent.get("name"))
    root = _safe_filename(display)

    work: List[Tuple[str, dict, bool]] = []  # (arcname, media, is_video)
    for key, _cat, _label in _SECTIONS:
        for i, m in enumerate(groups[key], 1):
            work.append((f"{root}/{_ZIP_FOLDERS[key]}/image-{i:02d}{_ext_for(m, False)}", m, False))
    if groups["video"]:
        work.append((f"{root}/{_ZIP_FOLDERS['video']}/introduction-video{_ext_for(groups['video'], True)}", groups["video"], True))
    if not work:
        raise HTTPException(404, "No media is available for this talent yet.")

    # Hard resource bound: refuse (don't queue) when all slots are busy.
    if _zip_slots.locked():
        raise HTTPException(503, "Download is busy right now. Please try again in a minute.", headers={"Retry-After": "30"})
    await _zip_slots.acquire()
    client = httpx.AsyncClient(follow_redirects=True, timeout=httpx.Timeout(60.0, connect=10.0))
    try:
        # Resolve every upstream URL BEFORE the first byte so a resolvable
        # failure (e.g. Stream MP4 not ready) is a clean HTTP error rather than
        # a truncated download.
        entries = []
        for arcname, m, is_video in work:
            url = await _upstream_url(client, m, is_video)
            if not url:
                raise HTTPException(502, "Some media is still being prepared. Please try again in a moment.")
            entries.append((arcname, _upstream_factory(client, url)))
    except BaseException:
        await client.aclose()
        _zip_slots.release()
        raise

    logger.info("talent media ZIP start: talent=%s files=%d", talent.get("id"), len(entries))

    released = False

    async def cleanup():
        # Idempotent: runs from the generator's finally AND from the response's
        # background hook, so a client that disconnects before the first byte
        # (generator never started) can't leak a slot or the HTTP client.
        nonlocal released
        if released:
            return
        released = True
        await client.aclose()
        _zip_slots.release()

    async def body():
        ok = False
        try:
            async for chunk in stream_zip(entries):
                yield chunk
            ok = True
        finally:
            await cleanup()
            logger.info("talent media ZIP %s: talent=%s", "complete" if ok else "ABORTED", talent.get("id"))

    zip_name = f"{root}.zip"
    return StreamingResponse(
        body(), media_type="application/zip", background=BackgroundTask(cleanup),
        headers={
            "Content-Disposition": f"attachment; filename=\"{zip_name}\"; filename*=UTF-8''{quote(zip_name)}",
            "Cache-Control": "private, no-store",
            "X-Content-Type-Options": "nosniff",
        },
    )


# ---------------------------------------------------------------------------
# WhatsApp: second message after the submission form
# ---------------------------------------------------------------------------
async def enqueue_media_link_message(
    submission: dict, event_type: str, *, group_name: str, project_id: Optional[str], project_name: str,
) -> bool:
    """Enqueue the media-link message for ONE submission event. Returns True if a
    job was enqueued. Never raises into the caller's notification flow beyond
    what the caller's own try/except handles; idempotent per event.

    event key = submission id + event type + the finalize stamp
    (`submitted_at` for NEW, `updated_at` for UPDATED), so a replay of the same
    event can never double-send while a genuine later resubmission still can —
    exactly mirroring how the form message itself is emitted."""
    tid = submission.get("talent_id")
    if not tid:
        return False
    talent = await db.talents.find_one({"id": tid}, {"_id": 0, "id": 1, "name": 1, "status": 1, "media_download_enabled": 1})
    if not talent or not is_media_download_enabled(talent):
        return False
    if str(talent.get("status") or "").lower() in _BLOCKED_STATUSES:
        return False
    token = await ensure_token(tid)
    if not token:
        return False

    stamp = submission.get("updated_at") if event_type == "SUBMISSION UPDATED" else submission.get("submitted_at")
    event_key = f"{submission.get('id')}:{event_type}:{stamp}"
    try:
        await db.talent_media_link_events.insert_one({
            "event_key": event_key, "submission_id": submission.get("id"), "talent_id": tid,
            "event_type": event_type, "created_at": _now(),
        })
    except DuplicateKeyError:
        logger.info("talent media link already enqueued for event %s — skipped", event_key)
        return False

    ts = _now()  # later than the form message(s) — worker sends in created_at order
    batch_id = str(uuid.uuid4())
    await db.whatsapp_batches.insert_one({
        "id": batch_id, "source_type": "INTERNAL_NOTIFICATION",
        "source_label": f"Talent Media Link for {project_name}", "project_id": project_id,
        "project_name": project_name, "template_id": "internal_notification_media_link",
        "template_slug": "internal_notification_media_link", "variable_data": {}, "media_url": None,
        "is_dry_run": False, "status": "pending", "total_jobs": 1, "sent_count": 0, "failed_count": 0,
        "unconfirmed_count": 0, "created_by": "system", "created_at": ts, "started_at": None, "completed_at": None,
    })
    await db.whatsapp_jobs.insert_one({
        "id": str(uuid.uuid4()), "batch_id": batch_id, "template_id": "internal_notification_media_link",
        "template_name": "Talent Media Link", "source": "INTERNAL_NOTIFICATION", "source_id": project_id,
        "recipient_kind": "INTERNAL_GROUP", "recipient_id": "internal_notification_group", "talent_id": None,
        "talent_name": group_name, "destination_type": "group", "destination": group_name,
        "message_body": build_media_link_message(talent.get("name"), token), "media_url": None,
        "is_dry_run": False, "status": "pending", "attempt_count": 0, "last_attempted_at": None,
        "sent_at": None, "error_message": None, "worker_picked_at": None, "created_at": ts,
    })
    logger.info("enqueued talent media link message for event %s", event_key)
    return True
