import React, { useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import { API } from "@/lib/api";
import { toast } from "sonner";
import Logo from "@/components/Logo";
import { Loader2, Mail, ArrowLeft } from "lucide-react";

/**
 * Public "Forgot password" page.
 * The backend ALWAYS returns a generic message regardless of whether the
 * email exists — the page therefore displays the same confirmation in both
 * cases. Reset links can only be generated by an admin via /admin/users.
 */
export default function ForgotPasswordPage() {
    const [email, setEmail] = useState("");
    const [busy, setBusy] = useState(false);
    const [done, setDone] = useState(false);
    const [serverMsg, setServerMsg] = useState("");

    const submit = async (e) => {
        e.preventDefault();
        if (!email.trim()) {
            toast.error("Enter your email");
            return;
        }
        setBusy(true);
        try {
            const { data } = await axios.post(`${API}/public/forgot-password`, {
                email: email.trim().toLowerCase(),
            });
            setServerMsg(
                data?.message ||
                    "If that account exists, contact your administrator to reset your password.",
            );
            setDone(true);
        } catch (err) {
            if (err?.response?.status === 429) {
                toast.error("Too many attempts. Please wait and try again later.");
            } else {
                // Any other error — mirror the generic message to avoid enumeration.
                setServerMsg(
                    "If that account exists, contact your administrator to reset your password.",
                );
                setDone(true);
            }
        } finally {
            setBusy(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#050505] text-[var(--tg-text)] tg-grain flex items-center justify-center px-4">
            <div className="w-full max-w-md">
                <div className="mb-8">
                    <Logo size="md" />
                </div>
                <p className="eyebrow mb-2">Account recovery</p>
                <h1 className="font-display text-3xl md:text-4xl mb-3">
                    Forgot password.
                </h1>

                {!done ? (
                    <>
                        <p className="text-sm text-white/60 mb-6 leading-relaxed">
                            Enter your registered email. If we find your account, we'll
                            let your administrator know to issue a secure reset link.
                        </p>
                        <form onSubmit={submit}>
                            <label className="block text-xs tg-mono text-white/50 mb-2">
                                Email
                            </label>
                            <div className="flex items-center border-b border-white/10 focus-within:border-white/40 mb-6">
                                <Mail className="w-3.5 h-3.5 text-white/30 mr-2" />
                                <input
                                    type="email"
                                    value={email}
                                    onChange={(e) => setEmail(e.target.value)}
                                    placeholder="you@talentgram.com"
                                    autoComplete="email"
                                    required
                                    disabled={busy}
                                    data-testid="forgot-email-input"
                                    className="flex-1 bg-transparent outline-none py-2 text-sm"
                                />
                            </div>
                            <button
                                type="submit"
                                disabled={busy}
                                data-testid="forgot-submit-btn"
                                className="w-full bg-white text-black py-3 rounded-sm text-sm font-medium inline-flex items-center justify-center gap-2 disabled:opacity-50"
                            >
                                {busy ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : null}
                                Request reset
                            </button>
                        </form>
                    </>
                ) : (
                    <div
                        className="border border-white/10 bg-white/5 p-5 rounded-sm"
                        data-testid="forgot-confirmation"
                    >
                        <p className="text-sm text-white/80 leading-relaxed">{serverMsg}</p>
                        <p className="text-[11px] text-white/40 mt-3">
                            For security reasons, we do not reveal whether an account exists for
                            this email. Please contact your administrator directly.
                        </p>
                    </div>
                )}

                <Link
                    to="/admin/login"
                    className="mt-6 inline-flex items-center gap-2 text-xs text-white/60 hover:text-white"
                    data-testid="forgot-back-link"
                >
                    <ArrowLeft className="w-3 h-3" />
                    Back to sign in
                </Link>
            </div>
        </div>
    );
}
